server:
  port: 9494
  shutdown: graceful

spring:
  jwt:
    secret: 33085d3cf14717d13f122979944e1e886636cc19e0f749dfbce423bb0031beae8b8758243ce109259c32a83a9325ef2c64433bc0339321d9540036a11884f8fc
    access-token:
      expires-in: 60000
    refresh-token:
      expires-in: 86400000

  application:
    name: book-store-coupon

  profiles:
    active: dev

springdoc:
  api-docs:
    path: /coupon-api
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /coupon-api.html
    disable-swagger-default-url: true

logging:
  file:
    path: ./logs

  level:
    com.netflix.discovery: ERROR
    com.netflix.eureka: ERROR

oritang:
  mysql:
    url: 3c7c814f85e54920b7c7e25c4253b687
    username: 7d697c13adf84236b7ca5ea60870ff9c
    password: 4766eb1428334444b8a10ce26bd980e8

