
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.orm.jdbc.bind: info
    org.springframework.transaction.interceptor: info

remote-addr: 133.186.134.30

#    shutdown: graceful
#
#  eureka:
#    instance:
#      instance-id: coupon
#      hostname: localhost
#      prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url:
#        defaultZone: http://admin:1234@localhost:8761/eureka
#
#  spring:
#    lifecycle:
#      timeout-per-shutdown-phase: 30s
#
#  management:
#    health:
#      status:
#        order: DOWN, UP
#    endpoint:
#      jolokia:
#        enabled: true
#      metrics:
#        enabled: true
#      pause:
#        enabled: true
#      resume:
#        enabled: true
#      restart:
#        enabled: true
#      shutdown:
#        enabled: true
#    endpoints:
#      web:
#        exposure:
#          include: '*'
#    info:
#      env:
#        enabled: true